# Copyright 2017 Atelier Disko. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8

env:
  - GO15VENDOREXPERIMENT=1

script:
  - make run-tests

matrix:
  fast_finish: true

notifications:
  email: false

sudo: false