// Copyright 2016 Atelier Disko. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package project

const WWW_KEEP string = "keep"
const WWW_DROP string = "drop"
const WWW_ADD string = "add"

type DomainDirective struct {
	FQDN      string
	WWW       string // keep, drop, add
	SSL       SSLDirective
	Auth      AuthDirective
	Aliases   []string
	Redirects []string
}

// TODO Allows special value "derived" where the User is taken
// from the project name. acme_stage -> acme, acme -> acme, acme_shop -> acme
const USER_DERIVED string = "!derived"

// TODO Allows special value "autogenerate" where an unsafe password
// is generated and mailed to the administrator.
const PASSWORD_AUTOGEN string = "!autogenerated"

// Auth is considered enabled, once a value for User is given. Empty
// passwords are not allowed.
type AuthDirective struct {
	User     string
	Password string
}

func (drv AuthDirective) isEnabled() bool {
	return drv.User != ""
}
